FROM golang:alpine
MAINTAINER "HashiCorp Terraform Team <terraform@hashicorp.com>"

ENV TERRAFORM_VERSION=0.7.5

RUN apk add --update git bash zip

WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/gettyimages/terraform.git ./ && \
    git checkout getty-vmware-patch && \
    /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["terraform"]
